//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bill_DBEntities : DbContext
    {
        public Bill_DBEntities()
            : base("name=Bill_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CounterMaster> CounterMasters { get; set; }
        public virtual DbSet<CustomerMaster> CustomerMasters { get; set; }
        public virtual DbSet<GoodsMaster> GoodsMasters { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<ItemMaster> ItemMasters { get; set; }
        public virtual DbSet<ItemTransaction> ItemTransactions { get; set; }
        public virtual DbSet<tblBudget> tblBudgets { get; set; }
        public virtual DbSet<tblBudgetMaster> tblBudgetMasters { get; set; }
        public virtual DbSet<tblGoogsTran> tblGoogsTrans { get; set; }
        public virtual DbSet<tblGroupMaster> tblGroupMasters { get; set; }
        public virtual DbSet<tblInvoice> tblInvoices { get; set; }
        public virtual DbSet<tblReceiptDetail> tblReceiptDetails { get; set; }
        public virtual DbSet<tblReceiptTransaction> tblReceiptTransactions { get; set; }
        public virtual DbSet<tblTanent> tblTanents { get; set; }
        public virtual DbSet<tblTaskTracker> tblTaskTrackers { get; set; }
    }
}
