//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsMaster
    {
        public int goodsId { get; set; }
        public string descriptionOfGoods { get; set; }
        public string hsn { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<int> cgst_p { get; set; }
        public Nullable<int> sgst_p { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public bool isActive { get; set; }
        public string unit { get; set; }
    }
}
