//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBudget
    {
        public int id { get; set; }
        public string group1 { get; set; }
        public string group2 { get; set; }
        public string group3 { get; set; }
        public string group4 { get; set; }
        public string details { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
