//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBudgetMaster
    {
        public int id { get; set; }
        public string month { get; set; }
        public string monthName { get; set; }
        public Nullable<int> montOrder { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
        public Nullable<System.DateTime> salaryDate { get; set; }
        public Nullable<decimal> need { get; set; }
        public Nullable<decimal> want { get; set; }
        public Nullable<decimal> saving { get; set; }
    }
}
