//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupMaster
    {
        public int id { get; set; }
        public string groupName { get; set; }
        public Nullable<bool> haveFixPrice { get; set; }
        public Nullable<decimal> priceGroup { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> group2int { get; set; }
    }
}
