//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGoogsTran
    {
        public int tGoodslno { get; set; }
        public string tInvoiceNo { get; set; }
        public string tGoodsDesc { get; set; }
        public Nullable<decimal> tQty { get; set; }
        public Nullable<decimal> tRate { get; set; }
        public Nullable<decimal> tValue { get; set; }
        public Nullable<decimal> cgstP { get; set; }
        public Nullable<decimal> cgstA { get; set; }
        public Nullable<decimal> scstP { get; set; }
        public Nullable<decimal> sgstA { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> grandTotal { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
