//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public int invSlno { get; set; }
        public int companyName { get; set; }
        public Nullable<System.DateTime> dateOfInvoice { get; set; }
        public Nullable<System.DateTime> agreementDate { get; set; }
        public string serialNoOfInvoice { get; set; }
        public string projectManager { get; set; }
        public string panNo { get; set; }
        public string projectName { get; set; }
        public string billTo { get; set; }
        public string billToGSTIN { get; set; }
        public string shipTo { get; set; }
        public string shipToGSTIN { get; set; }
        public Nullable<decimal> TotalInvoice { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
