//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceiptTransaction
    {
        public int trsp_id { get; set; }
        public Nullable<int> refNo { get; set; }
        public string trsp_goodsId { get; set; }
        public string trsp_goodsName { get; set; }
        public string trsp_hsn { get; set; }
        public Nullable<int> trsp_qty { get; set; }
        public Nullable<decimal> trsp_price { get; set; }
        public string trsp_valueOfGoods { get; set; }
        public Nullable<int> trsp_cgstP { get; set; }
        public Nullable<decimal> trsp_cgstA { get; set; }
        public Nullable<int> trsp_sgstP { get; set; }
        public Nullable<decimal> trsp_sgstA { get; set; }
        public Nullable<decimal> trsp_total { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string trsp_goodsUnit { get; set; }
    }
}
