//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceiptDetail
    {
        public int rsp_id { get; set; }
        public Nullable<int> refNo { get; set; }
        public Nullable<System.DateTime> receiptDate { get; set; }
        public int companyName { get; set; }
        public string rsp_name { get; set; }
        public string name_addr { get; set; }
        public string rsp_addrOfP { get; set; }
        public string rsp_addrOfD { get; set; }
        public Nullable<int> rsp_gstin { get; set; }
        public Nullable<decimal> rsp_grandTotal { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
