//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTanent
    {
        public int tanentId { get; set; }
        public string tanentName { get; set; }
        public string tanentaddr1 { get; set; }
        public string tanentaddr2 { get; set; }
        public string tanentaddr3 { get; set; }
        public string tanentGST { get; set; }
        public string bName { get; set; }
        public string acNo { get; set; }
        public string ifsc { get; set; }
        public string type { get; set; }
        public string branch { get; set; }
    }
}
